### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hxr404** [audieni/discord.py-heroku#10]
I followed your tutorial, but there is no pencil icon on heroku

**Comment by wuijx** [comment]
Hi, I'm assuming you're trying to turn your worker on under the resources menu. Here is a snippet of where the icon would be.

![image](https://user-images.githubusercontent.com/13210233/103232638-fb52b680-4908-11eb-861d-767e59522b93.png)

**Comment by hxr404** [comment]
no, the whole line/worker didnt show up. I had to delete everything and readd it
But I solved it rn, there was a dependency missing in the requirements.txt. idk why this would affect the other file but its fixed now.

Anyways thanks for your help. nice tutorial!
